### ISSUE TITLE
[header] Using header bb will cause root region to be larger then viewport frame disallowing async animations.

### ISSUE THREAD

**Issue by lightsofapollo** [mozilla-b2g/Gaia-UI-Building-Blocks#38]
To see this in action turn on layers.offmainthreadcomposition.log-animations and do an animation on a section with a header building block applied. This greatly effect the performance of any app with a "drawer" (about a 30 fps difference when animating that region).

Here are the relevant rules and how to disable them:

``` css

/* actually for issue https://github.com/mozilla-b2g/Gaia-UI-Building-Blocks/issues/37 */
.icon {
  text-indent: 0 !important;
  font-size: 0px;
  line-height: 2.5rem;
  margin-left: 0 !important;
}

body[role="application"] section[role="region"] > header h1 {
  margin-left: 0 !important;
}

body[role="application"] section[role="region"] > header {
  margin-left: 0px !important;
}

section[role="region"] > header:first-child h1 {
  margin: 0 !important;
}

```

Hopefully some of this is fixable in gecko upstream but if possible we should try to fix it here first so our animations perform better.
